version: '2.4'

services:
  postgres:
    container_name: postgres
    build: postgres/
    image: ronronan/postgresql-fr:14.0
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
    network_mode: bridge
    labels:
      - "traefik.enable=false"
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:6.0
    expose:
      - "80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@ronanmorel.fr
      PGADMIN_DEFAULT_PASSWORD: admin
    network_mode: bridge
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pgadmin.entrypoints=web"
      - "traefik.http.routers.pgadmin.rule=Host(`pgadmin.localhost`)"
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:15.0.2
    expose:
      - "8080"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: postgres
      DB_ADDR: 172.17.0.1
      DB_PORT: 5432
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: keycloak123
    volumes:
      - "./keycloak/morel-auth:/opt/jboss/keycloak/themes/morel-auth/"
    network_mode: bridge
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.keycloak.entrypoints=web"
      - "traefik.http.routers.keycloak.rule=Host(`keycloak.localhost`)"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
  traefik:
    container_name: traefik
    image: traefik:v2.5.3
    ports:
      - "80:80"
      - "8090:8080"
    expose:
      - "80"
      - "8080"
    volumes:
      - "./traefik/traefik.yml:/etc/traefik/traefik.yml"
      - "./traefik/proxy-config.yml:/etc/traefik/proxy-config.yml:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    network_mode: bridge

volumes:
  postgres-volume: