http:
  middlewares:
    frontend:
      stripPrefix:
        prefixes:
          - "/"
    backend:
      stripPrefix:
        prefixes:
          - "/"
  routers:
    frontend:
      rule: "Host(`monbudget.localhost`)"
      middlewares:
        - "frontend"
      service: "frontend"
      entryPoints: ["web"]
    backend:
      rule: "Host(`monbudget-backend.localhost`)"
      middlewares:
        - "backend"
      service: "backend"
      entryPoints: ["web"]
  services:
    frontend:
      loadBalancer:
        servers:
          - url: http://192.168.1.16:8080
    backend:
      loadBalancer:
        servers:
          - url: http://192.168.1.16:3000
