## traefik.yml

entryPoints:
  web:
    address: ":80"

# Docker configuration backend
providers:
  docker:
    defaultRule: "Host(`{{ trimPrefix `/` .Name }}.localhost`)"

# API and dashboard configuration
api:
  dashboard: true
  insecure: true
