## traefik.yml

entryPoints:
  web:
    address: ":80"

# Docker configuration backend
providers:
  docker:
    defaultRule: "Host(`{{ trimPrefix `/` .Name }}.localhost`)"
  file:
    filename: /etc/traefik/proxy-config.yml

# API and dashboard configuration
api:
  dashboard: true
  insecure: true
